version: "3.9"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - appnet

  toxiproxy:
    image: shopify/toxiproxy
    ports:
      - "8474:8474"
      - "8666:8666"
    networks:
      - appnet

  elastic_filter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8087:5000"
    depends_on:
      - toxiproxy
    networks:
      - appnet

  nginx:
    image: nginx
    ports:
      - "8088:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - appnet

networks:
  appnet:
